# Generated by Django 5.0.4 on 2024-05-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDFPageDataItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('page_number', models.IntegerField()),
                ('label_1', models.BooleanField(default=False)),
                ('label_2', models.BooleanField(default=False)),
                ('label_3', models.BooleanField(default=False)),
                ('label_4', models.BooleanField(default=False)),
                ('label_5', models.BooleanField(default=False)),
                ('label_6', models.BooleanField(default=False)),
                ('label_7', models.BooleanField(default=False)),
                ('label_8', models.BooleanField(default=False)),
                ('label_9', models.BooleanField(default=False)),
                ('label_10', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'myapp_pdfpagedataitem',
                'unique_together': {('filename', 'page_number')},
            },
        ),
    ]
